on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:

  AWS_REGION: 'eu-west-1' #Change to reflect your Region
  AWS_DEFAULT_REGION: 'eu-west-1' #Change to reflect your Region

# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  AssumeRoleAndCallIdentity:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
#      - name: configure aws credentialsa
#        uses: aws-actions/configure-aws-credentials@v1.7.0
#        with:
#          role-to-assume: arn:aws:iam::068008800301:role/GithubActions
#          role-session-name: GitHub_to_AWS_via_FederatedOIDC
#          aws-region: ${{ env.AWS_REGION }}

      - name: Test Python Lambda Functions
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Python tests
        run: cd backend && python -m unittest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.1.0'

      - name: Install Node.js dependencies and Build React APP
        run: cd frontend && npm install && npm run build

      - name: Install AWS CDK
        run: npm install -g aws-cdk
      - name: Build CDK app
        run: npm run build
      - name: Deploy CDK app
        run: cdk deploy --all --require-approval never